name: Deploy Project
on:
  push:
    branches:
      - main
      - 'dev-*'
    #paths-ignore:
    # - '.github/workflows/*'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Cache dependency
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: npm-${{ hashFiles('**/package-lock.json') }}
            - name: Npm Install
              run: npm ci
            - name: Test
              run: npm test
    build:
      needs: test
      runs-on: ubuntu-latest
      outputs:
        script-file: ${{ steps.publish-js-file.outputs.local-output }}
      steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Cache dependency
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: npm-${{ hashFiles('**/package-lock.json') }}
        - name: Npm Install
          run: npm ci
        - name: Build project
          run: npm run build
        - name: Publish JS file name
          id: publish-js-file
          run: find dist/assets/*.js -type f -execdir echo 'local-output={}' >> $GITHUB_OUTPUT ';'
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: dist-files
            path: dist
            #path: |
            #  dist
            #  package.json
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Get build artifacts
          uses: actions/download-artifact@v4
          with:
            name: dist-files
        - name: Output contents
          run: ls
        - name: Output file name
          run: echo "${{ needs.build.outputs.script-file }}"
        - name: Dpeloy
          run: echo "Deploying..."
          #comment
